image:
  repository: tccr.io/tccr/alpine
  pullPolicy: IfNotPresent
  tag: latest@sha256:ade0065e19edaa4f6903d464ee70605111a48394536deb94f31b661264704558

# don't install this unless you've followed our docs or talos docs!
# ref - https://www.talos.dev/v1.6/talos-guides/configuration/nvidia-gpu-proprietary/

# need to override naming
configmap:
  nvidia-device-plugin-configs:
    enabled: true
    data:
      # set "replicas" key to number of shares per original resource
      # example: 2 physical GPU * 5 replica = 10vGPU
      config: |
        version: v1
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 5

# don't edit below here
nvdp:
  runtimeClassName: nvidia
  gfd:
    enabled: true
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    enabled: false
